In [2]:
! pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x106bb23d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/pandas/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x106bb2670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/pandas/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x106bb2820>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/pandas/
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 667 kB/s eta 0:00:01
Requirement already satisfied: numpy>=1.22.4 in /Users/abhijain/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Collecting tzdata>=2022.7
  Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
     |████████████████████████████████| 348 kB 2.3 MB/s eta 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 356 kB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/abhijain/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, pandas
Successfully installed pandas-2.3.3 pytz-2026.3.post1 tzdata-2026.3
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [2]:
import pandas as pd

In [9]:
restaurant_data ={
    'table_no': [12 ,14 ,15],
    'bill_amount': [1250 ,890 ,2400],
    'waiter_name': ['Opbklo','kbklwa','chuhiChuha']
}

df = pd.DataFrame(restaurant_data)
print(df)
print()
print(type(df))
print()
print(df['bill_amount'])
print()
print(type(df['bill_amount']))

   table_no  bill_amount waiter_name
0        12         1250      Opbklo
1        14          890      kbklwa
2        15         2400  chuhiChuha

<class 'pandas.core.frame.DataFrame'>

0    1250
1     890
2    2400
Name: bill_amount, dtype: int64

<class 'pandas.core.series.Series'>

In [13]:
total_bill = [4700 ,8000 ,1200 ,500]
seriess = pd.Series(total_bill,index=['mon','tue','wed','thu'])
print(seriess)
print()
print(type(seriess))

mon    4700
tue    8000
wed    1200
thu     500
dtype: int64

<class 'pandas.core.series.Series'>

In [15]:
total_order = [45 ,30 ,15 ,60]
seriess = pd.Series(total_order,index=['Pizza','Burger','Pasta','Fries'])
print(seriess)

Pizza     45
Burger    30
Pasta     15
Fries     60
dtype: int64

In [14]:
app = {
    'Brand': ['Nike','Puma','Campus'],
    'Price': [3200 ,2799 ,1299],
    'In_Stock': ['Yes','Yes','No']
}
data = pd.DataFrame(app)
print(data)

    Brand  Price In_Stock
0    Nike   3200      Yes
1    Puma   2799      Yes
2  Campus   1299       No

In [3]:
df = pd.read_csv("tip.csv")
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [24]:
print(df.head(6))
print()
print(df.tail(6))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4

     total_bill   tip     sex smoker   day    time  size
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [26]:
print(df.shape)
print(df.columns)

(244, 7)
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [27]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB
None

In [28]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [37]:
print(df['day'].value_counts())
print()
print(df['day'].unique())
print(df['day'].nunique())

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

['Sun' 'Sat' 'Thur' 'Fri']
4

In [39]:
print(df['day'])
print(df['day'].shape)
print(df[['day']])
print(df[['day']].shape)

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: object
(244,)
      day
0     Sun
1     Sun
2     Sun
3     Sun
4     Sun
..    ...
239   Sat
240   Sat
241   Sat
242   Sat
243  Thur

[244 rows x 1 columns]
(244, 1)

In [3]:
df.groupby("day")['tip'].mean().round(2)

day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64

In [10]:
df['tip_pct']=round(df['tip']/df['total_bill']*100)
df.head(2)
df.groupby("day")['tip_pct'].mean().round(2)

day
Fri     16.95
Sat     15.37
Sun     16.70
Thur    16.11
Name: tip_pct, dtype: float64

In [6]:
df.groupby("day").agg(
    Bill_count = ("total_bill","size"),
    avg_bill = ("total_bill","mean"),
    avg_tip =("tip","mean")
)

      Bill_count   avg_bill   avg_tip
day
Fri           19  17.151579  2.734737
Sat           87  20.441379  2.993103
Sun           76  21.410000  3.255132
Thur          62  17.682742  2.771452

In [8]:
summary = df.groupby("day").agg(
    Bill_count = ("total_bill","size"),
    avg_bill = ("total_bill","mean"),
    avg_tip =("tip","mean")
).round(2)
summary

      Bill_count  avg_bill  avg_tip
day
Fri           19     17.15     2.73
Sat           87     20.44     2.99
Sun           76     21.41     3.26
Thur          62     17.68     2.77

In [27]:
flat =summary.index.to_list()
print(summary[summary["day"]==flat["sun"]])

KeyError: 'day'

In [21]:
print(summary.columns.to_list())
print(summary.index.to_list())

['Bill_count', 'avg_bill', 'avg_tip']
['Fri', 'Sat', 'Sun', 'Thur']

In [29]:
flat = summary.reset_index()
print(flat.columns.tolist())
flat.head()

['day', 'Bill_count', 'avg_bill', 'avg_tip']

    day  Bill_count  avg_bill  avg_tip
0   Fri          19     17.15     2.73
1   Sat          87     20.44     2.99
2   Sun          76     21.41     3.26
3  Thur          62     17.68     2.77

In [31]:
summary

      Bill_count  avg_bill  avg_tip
day
Fri           19     17.15     2.73
Sat           87     20.44     2.99
Sun           76     21.41     3.26
Thur          62     17.68     2.77

In [34]:
summary.to_csv("report.csv")

In [37]:
flat =pd.read_csv("report.csv")
flat.head()

    day  Bill_count  avg_bill  avg_tip
0   Fri          19     17.15     2.73
1   Sat          87     20.44     2.99
2   Sun          76     21.41     3.26
3  Thur          62     17.68     2.77

In [40]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [46]:
smk = df.groupby("smoker").agg(
    Bill_count = ("total_bill","size"),
    avg_bill = ("total_bill","mean"),
    avg_tip =("tip","mean")
).round(2)
smk

        Bill_count  avg_bill  avg_tip
smoker
No             151     19.19     2.99
Yes             93     20.76     3.01

In [47]:
smk.to_csv("smoker.csv")
hw = pd.read_csv("smoker.csv")
hw.head()

  smoker  Bill_count  avg_bill  avg_tip
0     No         151     19.19     2.99
1    Yes          93     20.76     3.01

In [50]:
df.loc[183]

total_bill     23.17
tip              6.5
sex             Male
smoker           Yes
day              Sun
time          Dinner
size               4
Name: 183, dtype: object

In [54]:
print(df.groupby("day")["tip"].idxmax())
print()
print(df.groupby("day")["tip"].idxmin())
print()
print(df.groupby("day")["tip"].max())
print()
print(df.groupby("day")["tip"].min())

day
Fri      95
Sat     170
Sun     183
Thur    141
Name: tip, dtype: int64

day
Fri      92
Sat      67
Sun       0
Thur    135
Name: tip, dtype: int64

day
Fri      4.73
Sat     10.00
Sun      6.50
Thur     6.70
Name: tip, dtype: float64

day
Fri     1.00
Sat     1.00
Sun     1.01
Thur    1.25
Name: tip, dtype: float64

In [57]:
print(df.loc[170])
print()
print(df.loc[92])

total_bill     50.81
tip             10.0
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               3
Name: 170, dtype: object

total_bill      5.75
tip              1.0
sex           Female
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 92, dtype: object

In [58]:
booking = pd.read_csv("/Users/abhijain/Documents/AI-ML-class-practice-/data/bookings.csv")

In [59]:
booking

    booking_id        customer  day    time  party_size
0          101     ravi sharma  Sat  Dinner         4.0
1          102      PRIYA IYER  Sat  Dinner         2.0
2          103    Ravi Sharma   Sun   Lunch         NaN
3          104      amit kumar  Sun  Dinner         6.0
4          105     priya  iyer  Fri  Dinner         NaN
5          106     RAVI SHARMA  Sat   Lunch         3.0
6          107       sana khan  Sat   Lunch         NaN
7          108      Amit Kumar  Sat  Dinner         5.0
8          109      vikram rao  Sun  Dinner         2.0
9          110      Sana  Khan  Fri  Dinner         4.0
10         111      priya iyer  Sat   Lunch         NaN
11         112      VIKRAM RAO  Sun   Lunch         3.0

In [60]:
booking["customer"].nunique()

12

In [61]:
booking["customer"].str.lower().str.strip()

0     ravi sharma
1      priya iyer
2     ravi sharma
3      amit kumar
4     priya  iyer
5     ravi sharma
6       sana khan
7      amit kumar
8      vikram rao
9      sana  khan
10     priya iyer
11     vikram rao
Name: customer, dtype: object

In [62]:
booking["customer"].nunique()

12